In [1]:
import cv2
import numpy as np

In [97]:
# Đọc ảnh từ tệp jpg
rgb_image = cv2.imread('cat.jpg')

In [69]:
# Kiểm tra xem ảnh có tồn tại không
if rgb_image is None:
    print("Không thể đọc ảnh. Hãy đảm bảo rằng đường dẫn và tên tệp là chính xác.")
    exit()

# Hiển thị ảnh trên cửa sổ mới
cv2.imshow('Original Image', rgb_image)
cv2.waitKey(0)

-1

In [62]:
# Viết lên ảnh một dòng chữ "Open CV"
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(rgb_image, 'Open CV', (10, 50), font, 1, (255, 255, 255), 2, cv2.LINE_AA)

array([[[ 39,  69,  34],
        [ 38,  69,  32],
        [ 37,  68,  31],
        ...,
        [ 39,  90,  40],
        [ 41,  91,  43],
        [ 43,  93,  45]],

       [[ 35,  66,  27],
        [ 35,  66,  27],
        [ 35,  66,  27],
        ...,
        [ 41,  92,  42],
        [ 41,  92,  42],
        [ 42,  93,  43]],

       [[ 36,  67,  28],
        [ 37,  68,  29],
        [ 37,  68,  29],
        ...,
        [ 42,  93,  43],
        [ 42,  93,  43],
        [ 42,  94,  41]],

       ...,

       [[ 14,  53, 122],
        [  9,  48, 116],
        [ 12,  50, 115],
        ...,
        [ 50, 138,  72],
        [ 47, 138,  69],
        [ 47, 139,  68]],

       [[ 37,  75, 139],
        [ 37,  75, 139],
        [ 45,  82, 142],
        ...,
        [ 48, 136,  70],
        [ 48, 136,  70],
        [ 48, 137,  68]],

       [[ 62, 100, 158],
        [ 66, 103, 159],
        [ 73, 110, 166],
        ...,
        [ 48, 134,  70],
        [ 48, 135,  69],
        [ 48, 135,  69]]

In [93]:
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(rgb_image, 'Lê Hoàng Minh', (10, 100), font, 1, (255, 255, 255), 1, cv2.LINE_AA)

array([[[ 39,  69,  34],
        [ 38,  69,  32],
        [ 37,  68,  31],
        ...,
        [ 39,  90,  40],
        [ 41,  91,  43],
        [ 43,  93,  45]],

       [[ 35,  66,  27],
        [ 35,  66,  27],
        [ 35,  66,  27],
        ...,
        [ 41,  92,  42],
        [ 41,  92,  42],
        [ 42,  93,  43]],

       [[ 36,  67,  28],
        [ 37,  68,  29],
        [ 37,  68,  29],
        ...,
        [ 42,  93,  43],
        [ 42,  93,  43],
        [ 42,  94,  41]],

       ...,

       [[ 14,  53, 122],
        [  9,  48, 116],
        [ 12,  50, 115],
        ...,
        [ 50, 138,  72],
        [ 47, 138,  69],
        [ 47, 139,  68]],

       [[ 37,  75, 139],
        [ 37,  75, 139],
        [ 45,  82, 142],
        ...,
        [ 48, 136,  70],
        [ 48, 136,  70],
        [ 48, 137,  68]],

       [[ 62, 100, 158],
        [ 66, 103, 159],
        [ 73, 110, 166],
        ...,
        [ 48, 134,  70],
        [ 48, 135,  69],
        [ 48, 135,  69]]

In [94]:
# Hiển thị ảnh với dòng chữ
cv2.imshow('Image with Text', rgb_image)
cv2.waitKey(0)

-1

In [12]:
# Ghi ảnh mới ra tệp
cv2.imwrite('imagewithOPENCV-Text.jpg', rgb_image)

True

In [10]:
colors = {'blue': (255, 0, 0), 'green': (0, 255, 0), 'red': (0, 0, 255), 'yellow':
(0, 255, 255), 'magenta': (255, 0, 255), 'cyan': (255, 255, 0), 'white': (255, 255,
255), 'black': (0, 0, 0), 'gray': (125, 125, 125), 'rand': np.random.randint(0,
high=256, size=(3,)).tolist(), 'dark_gray': (50, 50, 50), 'light_gray': (220, 220,
220)}

In [11]:
rgb_image = np.zeros((500, 500, 3), dtype="uint8")

In [29]:
(height, width, division) = rgb_image.shape

In [27]:
print(i)

(463, 703, 3)


In [104]:
separation = 40
for key in colors:
    cv2.line(rgb_image, (0, separation), (width, separation), colors[key], 10)
    separation += 40

In [105]:
cv2.imshow('Image with Text', rgb_image)
cv2.waitKey(0)

-1

In [52]:
cv2.line(rgb_image, (0, 400), (400, 0), colors['blue'], 1)

array([[[ 39,  69,  34],
        [ 38,  69,  32],
        [ 37,  68,  31],
        ...,
        [ 39,  90,  40],
        [ 41,  91,  43],
        [ 43,  93,  45]],

       [[ 35,  66,  27],
        [ 35,  66,  27],
        [ 35,  66,  27],
        ...,
        [ 41,  92,  42],
        [ 41,  92,  42],
        [ 42,  93,  43]],

       [[ 36,  67,  28],
        [ 37,  68,  29],
        [ 37,  68,  29],
        ...,
        [ 42,  93,  43],
        [ 42,  93,  43],
        [ 42,  94,  41]],

       ...,

       [[ 14,  53, 122],
        [  9,  48, 116],
        [ 12,  50, 115],
        ...,
        [ 50, 138,  72],
        [ 47, 138,  69],
        [ 47, 139,  68]],

       [[ 37,  75, 139],
        [ 37,  75, 139],
        [ 45,  82, 142],
        ...,
        [ 48, 136,  70],
        [ 48, 136,  70],
        [ 48, 137,  68]],

       [[ 62, 100, 158],
        [ 66, 103, 159],
        [ 73, 110, 166],
        ...,
        [ 48, 134,  70],
        [ 48, 135,  69],
        [ 48, 135,  69]]

In [96]:
cv2.imshow('Original Image', rgb_image)
cv2.waitKey(0)

-1

In [51]:
cv2.line(rgb_image, (400, 0), (0, 400), colors['blue'], 1)

array([[[ 39,  69,  34],
        [ 38,  69,  32],
        [ 37,  68,  31],
        ...,
        [ 39,  90,  40],
        [ 41,  91,  43],
        [ 43,  93,  45]],

       [[ 35,  66,  27],
        [ 35,  66,  27],
        [ 35,  66,  27],
        ...,
        [ 41,  92,  42],
        [ 41,  92,  42],
        [ 42,  93,  43]],

       [[ 36,  67,  28],
        [ 37,  68,  29],
        [ 37,  68,  29],
        ...,
        [ 42,  93,  43],
        [ 42,  93,  43],
        [ 42,  94,  41]],

       ...,

       [[ 14,  53, 122],
        [  9,  48, 116],
        [ 12,  50, 115],
        ...,
        [ 50, 138,  72],
        [ 47, 138,  69],
        [ 47, 139,  68]],

       [[ 37,  75, 139],
        [ 37,  75, 139],
        [ 45,  82, 142],
        ...,
        [ 48, 136,  70],
        [ 48, 136,  70],
        [ 48, 137,  68]],

       [[ 62, 100, 158],
        [ 66, 103, 159],
        [ 73, 110, 166],
        ...,
        [ 48, 134,  70],
        [ 48, 135,  69],
        [ 48, 135,  69]]

In [103]:
cv2.imshow('Original Image', rgb_image)
cv2.waitKey(0)

-1

In [102]:
cv2.line(rgb_image, (0, 0), (width, height), colors['green'], 3)
cv2.line(rgb_image, (0, 400), (400, 0), colors['blue'], 10)
cv2.line(rgb_image, (200, 0), (200, 400), colors['red'], 3)
cv2.line(rgb_image, (0, 200), (400, 200), colors['yellow'], 10)

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [ 39,  90,  40],
        [ 41,  91,  43],
        [ 43,  93,  45]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [ 41,  92,  42],
        [ 41,  92,  42],
        [ 42,  93,  43]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [ 42,  93,  43],
        [ 42,  93,  43],
        [ 42,  94,  41]],

       ...,

       [[ 14,  53, 122],
        [  9,  48, 116],
        [ 12,  50, 115],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[ 37,  75, 139],
        [ 37,  75, 139],
        [ 45,  82, 142],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[ 62, 100, 158],
        [ 66, 103, 159],
        [ 73, 110, 166],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

In [76]:
rgb_image.fill(255)

In [83]:
rgb_image.show()

AttributeError: 'numpy.ndarray' object has no attribute 'show'

In [100]:
rgb_image = cv2.imread('cat.jpg')
cv2.rectangle(rgb_image, (10, 50), (100, 300), colors['green'], 3)
cv2.rectangle(rgb_image, (80, 50), (130, 300), colors['blue'], -1)
cv2.rectangle(rgb_image, (150, 50), (350, 100), colors['red'], -1)
cv2.rectangle(rgb_image, (150, 150), (350, 300), colors['cyan'], 10)

array([[[ 39,  69,  34],
        [ 38,  69,  32],
        [ 37,  68,  31],
        ...,
        [ 39,  90,  40],
        [ 41,  91,  43],
        [ 43,  93,  45]],

       [[ 35,  66,  27],
        [ 35,  66,  27],
        [ 35,  66,  27],
        ...,
        [ 41,  92,  42],
        [ 41,  92,  42],
        [ 42,  93,  43]],

       [[ 36,  67,  28],
        [ 37,  68,  29],
        [ 37,  68,  29],
        ...,
        [ 42,  93,  43],
        [ 42,  93,  43],
        [ 42,  94,  41]],

       ...,

       [[ 14,  53, 122],
        [  9,  48, 116],
        [ 12,  50, 115],
        ...,
        [ 50, 138,  72],
        [ 47, 138,  69],
        [ 47, 139,  68]],

       [[ 37,  75, 139],
        [ 37,  75, 139],
        [ 45,  82, 142],
        ...,
        [ 48, 136,  70],
        [ 48, 136,  70],
        [ 48, 137,  68]],

       [[ 62, 100, 158],
        [ 66, 103, 159],
        [ 73, 110, 166],
        ...,
        [ 48, 134,  70],
        [ 48, 135,  69],
        [ 48, 135,  69]]